#!/usr/bin/env bash

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 ENVIRONMENT POD_NAME" >&2
  exit 1
fi

# exit on any failing command
set -e

environment_name=$1
pod_name=$2
command=${3:-bash}

# common call
source $(dirname $(realpath ${0}))/load_environment_config

matching_pod_name=$(kubectl -n ${environment_namespace} get pods | grep ${pod_name} | grep Running  | head -n 1 | cut -d ' ' -f 1)

if [ "$matching_pod_name"  = '' ]; then
  echo "No matching pod with name \"$pod_name\" found"
else
   kubectl -n ${environment_namespace} exec -ti ${matching_pod_name} -- ${command}
fi
