#!/usr/bin/env bash

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 ENVIRONMENT POD_NAME" >&2
  exit 1
fi

# exit on any failing command
set -e

environment_name=$1
pod_name=$2
command=${3:-bash}

# common call
called_file=$0
called_dir=$(realpath `dirname ${called_file}`)
tools_dir=$(dirname `realpath ${called_file}`)
source ${tools_dir}/load_environment_config ${called_dir}

matching_pod_name=$(kubectl -n ${environment_namespace} get pods | grep ${pod_name} | grep Running  | head -n 1 | cut -d ' ' -f 1)

if [ "$matching_pod_name"  = '' ]; then
  echo "No matching pod with name \"$pod_name\" found"
else
   kubectl -n ${environment_namespace} exec -ti ${matching_pod_name} -- ${command}
fi
