#!/usr/bin/env bash
source "$(dirname "$(realpath "$0")")/common"
parse_common_options "$@"
set -- "${command_args[@]}"
require_usage 1 'DEPLOYMENT [RESOURCE] [-c CONTAINER] [-- COMMAND ARG...]' "$@"
deployment_name=$1
shift
resource=
container_args=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --) shift; break;;
    -c|--container) [ "$#" -ge 2 ] || die '--container requires a name'; container_args=(-c "$2"); shift 2;;
    -*) usage_error "Unknown exec option: $1";;
    *) [ -z "$resource" ] || die 'Use -- before the command to execute'; resource=$1; shift;;
  esac
done
if [ "$#" -eq 0 ]; then set -- sh; fi
require_cluster=1
source "$tools_dir/load_deployment_config"
source "$tools_dir/select_resource"
exec_in_pod "${container_args[@]}" "$resource" -- "$@"
