#!/usr/bin/env bash
source "$(dirname "$(realpath "$0")")/common"
parse_common_options "$@"
set -- "${command_args[@]}"
require_usage 1 'DEPLOYMENT KUBECTL_ARGS...' "$@"
deployment_name=$1
shift
require_cluster=1
source "$tools_dir/load_deployment_config"
kubectl "${kube_args[@]}" "$@"
