#!/usr/bin/env bash

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 ENVIRONMENT" >&2
  exit 1
fi

# exit on any failing command
set -e

environment_name=$1
kubectl_args=${@:2}

# common call
source $(dirname $(realpath ${0}))/load_environment_config

kubectl -n ${environment_namespace} ${kubectl_args}
