#!/usr/bin/env bash
source "$(dirname "$(realpath "$0")")/common"
parse_common_options "$@"
set -- "${command_args[@]}"
require_usage 1 'DEPLOYMENT [RESOURCE] [KUBECTL_LOGS_OPTIONS]' "$@"
deployment_name=$1
shift
resource=
if [ "$#" -gt 0 ] && [[ "$1" != -* ]]; then resource=$1; shift; fi
require_cluster=1
source "$tools_dir/load_deployment_config"
source "$tools_dir/select_resource"
kubectl "${kube_args[@]}" logs "$resource" "$@"
