#!/usr/bin/env bash
parse_common_options "$@"
set -- "${command_args[@]}"
require_usage 1 'DEPLOYMENT [HELM_OPTIONS]' "$@"
deployment_name=$1
shift
require_cluster=1
require_release=1
source "$tools_dir/load_deployment_config"
need_command helm
print_target
helm "$release_action" "$release" "${helm_connection_args[@]}" "$@"
