#!/usr/bin/env bash

if [ "$#" -lt 3 ]; then
  echo "Usage: $0 ACTION ENVIRONMENT VALUES_FILE_PATH" >&2
  exit 1
fi

# exit on any failing command
set -e

action=$1
environment_name=$2
values_path=$3

# common call
called_file=$0
called_dir=$(realpath `dirname ${called_file}`)
tools_dir=$(dirname `realpath ${called_file}`)
source ${tools_dir}/load_environment_config ${called_dir}

encrypt_chart_dir="${tools_dir}/secrets-chart"

helm --values ${values_path} --set encryptionKey=${environment_encryption_key} template ${encrypt_chart_dir} --set action=${action}
